import io
from typing import Optional

from kubernetes.client.configuration import Configuration
from urllib3 import BaseHTTPResponse

class RESTResponse(io.IOBase): ...

class RESTClientObject:
    def __init__(self, configuration: Configuration, pools_size: int, maxsize: Optional[int]): ...
    def request(
        self, method: str, url: str, query_params, headers, body, post_params, _preload_content, _request_timeout
    ) -> BaseHTTPResponse: ...
    def GET(self, url: str, query_params, headers, _preload_content, _request_timeout) -> BaseHTTPResponse: ...
    def HEAD(self, url: str, query_params, headers, _preload_content, _request_timeout) -> BaseHTTPResponse: ...
    def OPTIONS(
        self, url: str, query_params, headers, body, post_params, _preload_content, _request_timeout
    ) -> BaseHTTPResponse: ...
    def DELETE(self, url: str, query_params, headers, body, _preload_content, _request_timeout) -> BaseHTTPResponse: ...
    def POST(
        self, url: str, query_params, headers, body, post_params, _preload_content, _request_timeout
    ) -> BaseHTTPResponse: ...
    def PUT(
        self, url: str, query_params, headers, body, post_params, _preload_content, _request_timeout
    ) -> BaseHTTPResponse: ...
    def PATCH(
        self, url: str, query_params, headers, body, post_params, _preload_content, _request_timeout
    ) -> BaseHTTPResponse: ...
