import typing

class V1SuccessPolicyRule:
    succeeded_count: typing.Optional[int]
    succeeded_indexes: typing.Optional[str]
    def __init__(
        self, *, succeeded_count: typing.Optional[int] = ..., succeeded_indexes: typing.Optional[str] = ...
    ) -> None: ...
    def to_dict(self) -> typing.Any: ...
